services:
  mongodb:
    image: mongo
    container_name: mongo_db
    ports:
      - 27017:27017
    volumes:
      - mongo:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=jcmagal
      - MONGO_INITDB_ROOT_PASSWORD=jcmagal
  mongo-express:
    image: mongo-express
    container_name: mongo_express
    restart: always
    ports:
      - 8083:8083
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=jcmagal
      - ME_CONFIG_MONGODB_ADMINPASSWORD=jcmagal
      - ME_CONFIG_MONGODB_SERVER=mongodb
    depends_on:
      - mongodb
volumes:
  mongo: {}